### ISSUE TITLE
Approval with --ask flag deletes the file instead of overwriting it

### ISSUE THREAD

**Issue by kytrinyx** [kytrinyx/approvals#62]
It looks like when the arguments were reversed in the file we didn't also reverse the order of files in the `mv` command.

@randycoulman I'm fixing it now--you'll want to be sure to upgrade before RailsConf.

**Comment by randycoulman** [comment]
I thought I did reverse that. Thanks for catching my oversight.

Randy

**Comment by kytrinyx** [comment]
It's all good--just glad we caught it before you had 150 confused workshop attendees :)

**Comment by kytrinyx** [comment]
Also, you probably did fix it. I recall something about a merge conflict that I probably got wrong.
